<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="5" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-18T22:02:03 PDT" name="Suite" finished-at="2023-03-18T22:02:42 PDT" duration-ms="39010">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationsTest.validationLogin()[pri:0, instance:aclabrador.Tests.ErrorValidationsTest@2b76ff4e]" name="validationLogin" class="aclabrador.Tests.ErrorValidationsTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:aclabrador.Tests.SubmitOrderTest@5b6ec132]" name="submitOrder" class="aclabrador.Tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2023-03-18T22:02:03 PDT" name="SubmitOrder" finished-at="2023-03-18T22:02:30 PDT" duration-ms="26186">
      <class name="aclabrador.Tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplications()[pri:0, instance:aclabrador.Tests.SubmitOrderTest@5b6ec132]" started-at="2023-03-18T22:02:04 PDT" name="launchApplications" finished-at="2023-03-18T22:02:10 PDT" duration-ms="6221" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplications -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:aclabrador.Tests.SubmitOrderTest@5b6ec132]" started-at="2023-03-18T22:02:10 PDT" name="submitOrder" data-provider="getData" finished-at="2023-03-18T22:02:14 PDT" duration-ms="4186" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{prodName=ADIDAS ORIGINAL, pass=Cecy19*7, email=aclabrador1907@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="launchApplications()[pri:0, instance:aclabrador.Tests.SubmitOrderTest@5b6ec132]" started-at="2023-03-18T22:02:14 PDT" name="launchApplications" finished-at="2023-03-18T22:02:19 PDT" duration-ms="4838" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplications -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:aclabrador.Tests.SubmitOrderTest@5b6ec132]" started-at="2023-03-18T22:02:19 PDT" name="submitOrder" data-provider="getData" finished-at="2023-03-18T22:02:23 PDT" duration-ms="4238" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{prodName=ZARA COAT 3, pass=Cecy19*7, email=aclabrador1907@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="launchApplications()[pri:0, instance:aclabrador.Tests.SubmitOrderTest@5b6ec132]" started-at="2023-03-18T22:02:23 PDT" name="launchApplications" finished-at="2023-03-18T22:02:28 PDT" duration-ms="5173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplications -->
        <test-method signature="verifyProdOrder()[pri:0, instance:aclabrador.Tests.SubmitOrderTest@5b6ec132]" started-at="2023-03-18T22:02:28 PDT" name="verifyProdOrder" finished-at="2023-03-18T22:02:30 PDT" depends-on-methods="aclabrador.Tests.SubmitOrderTest.submitOrder" duration-ms="1223" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProdOrder -->
      </class> <!-- aclabrador.Tests.SubmitOrderTest -->
    </test> <!-- SubmitOrder -->
    <test started-at="2023-03-18T22:02:30 PDT" name="ErrorValidations" finished-at="2023-03-18T22:02:42 PDT" duration-ms="12443">
      <class name="aclabrador.Tests.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplications()[pri:0, instance:aclabrador.Tests.ErrorValidationsTest@2b76ff4e]" started-at="2023-03-18T22:02:30 PDT" name="launchApplications" finished-at="2023-03-18T22:02:35 PDT" duration-ms="5240" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplications -->
        <test-method retried="true" signature="validationLogin()[pri:0, instance:aclabrador.Tests.ErrorValidationsTest@2b76ff4e]" started-at="2023-03-18T22:02:35 PDT" name="validationLogin" finished-at="2023-03-18T22:02:36 PDT" duration-ms="1006" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or password no.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password no.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at aclabrador.Tests.ErrorValidationsTest.validationLogin(ErrorValidationsTest.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationLogin -->
        <test-method is-config="true" signature="launchApplications()[pri:0, instance:aclabrador.Tests.ErrorValidationsTest@2b76ff4e]" started-at="2023-03-18T22:02:36 PDT" name="launchApplications" finished-at="2023-03-18T22:02:41 PDT" duration-ms="4915" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplications -->
        <test-method signature="validationLogin()[pri:0, instance:aclabrador.Tests.ErrorValidationsTest@2b76ff4e]" started-at="2023-03-18T22:02:41 PDT" name="validationLogin" finished-at="2023-03-18T22:02:42 PDT" duration-ms="725" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or password no.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password no.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at aclabrador.Tests.ErrorValidationsTest.validationLogin(ErrorValidationsTest.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationLogin -->
      </class> <!-- aclabrador.Tests.ErrorValidationsTest -->
    </test> <!-- ErrorValidations -->
  </suite> <!-- Suite -->
</testng-results>
